FROM drupal:8

# See https://github.com/chialab/docker-php/pull/74/files
ENV PATH=$PATH:/root/composer2/vendor/bin:/root/composer1/vendor/bin \
  COMPOSER_ALLOW_SUPERUSER=1 \
  COMPOSER_HOME=/root/composer2 \
  COMPOSER1_HOME=/root/composer1

COPY docker-resources/9/composer.json /composer-file/composer.json
COPY docker-resources/9/build.sh /build.sh

RUN /build.sh

WORKDIR /var/www/html

EXPOSE 80
