FROM drupal:11-fpm-alpine

COPY docker-resources /docker-resources
RUN apk add --no-cache bash && \
  cd /docker-resources/11-fpm-alpine-dev && \
  ./build.sh && \
  rm -rf /docker-resources

WORKDIR /var/www/html

EXPOSE 80
