FROM drupal:8

RUN curl -sS https://getcomposer.org/installer | php && \
  mv composer.phar /usr/local/bin/composer && \
  apt-get update && \
  apt-get install -y --no-install-recommends mysql-client git unzip && \
  rm -rf /var/lib/apt/lists/*

COPY docker-resources/9/composer.json /var/www/html/composer.json

RUN rm composer.lock && \
  composer install && \
  cat /var/www/html/core/lib/Drupal.php|grep VERS && \
  ln -s /var/www/html/vendor/bin/drush /bin/drush && \
  drush -v

EXPOSE 80
