FROM drupal:11-fpm-alpine

WORKDIR /var/www/html
COPY docker-resources /docker-resources
RUN apk add --no-cache bash && cd /docker-resources/11-fpm-alpine && ./build.sh && rm -rf /docker-resources

EXPOSE 80
