FROM drupal:8

RUN curl -sS https://getcomposer.org/installer | php && \
  mv composer.phar /usr/local/bin/composer && \
  apt-get update && \
  apt-get install -y --no-install-recommends mariadb-client git unzip && \
  rm -rf /var/lib/apt/lists/*

COPY docker-resources/9/composer.json /opt/drupal/composer.json

RUN rm composer.lock && \
  export COMPOSER_MEMORY_LIMIT=-1 && \
  composer install && \
  cat /var/www/html/core/lib/Drupal.php|grep VERS && \
  ln -s /opt/drupal/vendor/bin/drush /bin/drush && \
  drush -v

EXPOSE 80
