VERSION="$1"
BASEIMAGEVERSION="$2"
PLATFORMS="$3"

echo "*"
echo "**"
echo "***"
echo "****"
echo "*****"
echo "******"
echo "*******"
echo "********"
echo "*********"
echo "**********"
echo "***********"
echo "************"
echo "*************"
echo "** REBUILDING MULTI-ARCH VERSION $VERSION"
echo "** USING BASE IMAGE $BASEIMAGEVERSION"
echo "** USING PLATFORM(S) $PLATFORMS"
echo "*************"

# Start by getting the latest version of the official drupal image
docker pull drupal:"$BASEIMAGEVERSION"

# Rebuild the entire thing
docker buildx build -f="Dockerfile-$VERSION" -t dcycle/drupal:"$VERSION" --platform "$PLATFORMS" --push .
docker buildx build -f="Dockerfile-$VERSION" -t dcycle/drupal:"$VERSION.$DATE" --platform "$PLATFORMS" --push .

echo "*************"
echo "** DONE REBUILDING MULTI-ARCH VERSION $VERSION"
echo "** DONE USING BASE IMAGE $BASEIMAGEVERSION"
echo "** DONE USING PLATFORM(S) $PLATFORMS"
echo "*************"
echo "************"
echo "***********"
echo "**********"
echo "*********"
echo "********"
echo "*******"
echo "******"
echo "*****"
echo "****"
echo "***"
echo "**"
echo "*"
