name: Drupal Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Enable manual trigger

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Docker cache (updated to v3)
      - name: Set up Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Remove conflicting containerd packages
      - name: Remove conflicting containerd packages
        run: |
          sudo apt-get remove -y containerd containerd.io
          sudo apt-get autoremove -y

      # Step 5: Clean apt cache and update
      - name: Clean apt cache and update
        run: |
          sudo apt-get clean
          sudo apt-get update

      # Step 6: Install Docker
      - name: Install Docker
        run: |
          sudo apt-get install -y docker.io

      # Step 7: Debugging info (optional)
      - name: Debugging Docker environment
        run: |
          docker --version
          docker info
          echo "Current working directory:"
          pwd
          echo "Listing files in the repository:"
          ls -la

      # Step 8: Run the test.sh script
      - name: Run test.sh script
        run: |
          chmod +x ./test.sh
          ./test.sh
