name: Drupal Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enable manual trigger

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Docker cache (updated to v3)
      - name: Set up Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Remove conflicting containerd package
      - name: Remove conflicting containerd package
        run: |
          sudo apt-get remove -y containerd

      # Step 5: Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Step 6: Debugging info (optional)
      - name: Debugging Docker environment
        run: |
          docker --version
          docker info
          echo "Current working directory:"
          pwd
          echo "Listing files in the repository:"
          ls -la

      # Step 7: Run the test.sh script
      - name: Run test.sh script
        run: |
          chmod +x ./test.sh
          ./test.sh
